#include <map>
#include <set>
#include <list>
#include <cmath>
#include <ctime>
#include <deque>
#include <mutex>
#include <queue>
#include <stack>
#include <atomic>
#include <bitset>
#include <cctype>
#include <cfloat>
#include <chrono>
#include <cstdio>
#include <iosfwd>
#include <limits>
#include <memory>
#include <string>
#include <thread>
#include <vector>
#include <cassert>
#include <climits>
#include <cstdarg>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <sstream>
#include <stdio.h>
#include <utility>
#include <iostream>
#include <iterator>
#include <cstdlib>
#include <typeinfo>
#include <algorithm>
#include <unordered_map>
// range-v3
#include <range/v3/all.hpp>
// Eigen
#include <Eigen/LU>
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/Sparse>
#include <Eigen/Cholesky>
#include <Eigen/Geometry>
#include <Eigen/StdVector>
#include <Eigen/SparseCholesky>
// OpenCV2
#include <opencv/cv.h>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/features2d.hpp>
// pangolin
#include <pangolin/pangolin.h>
// spdlog
#include <spdlog/spdlog.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <spdlog/sinks/stdout_color_sinks.h>

